<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.skybooker</groupId>
    <artifactId>skybooker-backend</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>SkyBooker Backend</name>
    <description>Aggregator POM for all SkyBooker microservices</description>

    <modules>
        <module>service-registry</module>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>flight-service</module>
        <module>booking-service</module>
        <module>seat-service</module>
        <module>passenger-service</module>
        <module>payment-service</module>
        <module>notification-service</module>
        <module>airline-service</module>
    </modules>

</project>
