server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: airline-service
          uri: lb://airline-service
          predicates:
            - Path=/api/v1/airlines/**

        - id: airport-routes-via-airline-service
          uri: lb://airline-service
          predicates:
            - Path=/api/v1/airports/**

        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/v1/flights/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"