server:
  port: 8086

spring:
  application:
    name: seat-service

  datasource:
    url: jdbc:mysql://localhost:3306/skybooker_seat_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: yukta@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    secret: 9f3c7a1d5e8b4c6a2f9d1b7c3e6a8d5f2c4b7a9e1d6c3f8b2a5d7e9c1f3e6a8